schemaVersion: 2.2.0
components:
  - name: gitlab-vscode-extension
    attributes:
      gl/inject-editor: true
    container:
      image: registry.gitlab.com/gitlab-org/gitlab-build-images:workspaces-web-ide
      memoryLimit: 3072Mi
      memoryRequest: 3072Mi
      env:
        - name: MISE_TRUSTED_CONFIG_PATHS
          value: /projects/gitlab-vscode-extension
commands:
  - id: install-dependencies
    exec:
      component: gitlab-vscode-extension
      commandLine: "cd /projects/gitlab-vscode-extension && mise install node && mise install && npm install"
events:
  postStart:
    - install-dependencies
