import { log } from '../../common/log';
import { getGitLabService } from '../gitlab/get_gitlab_service';
import { ProjectInRepository } from '../gitlab/new_project';
import { GqlDiffPositionInput } from '../gitlab/graphql/create_diff_comment';
import { ReviewComment, MRReviewContext } from './types';

/**
 * 在 GitLab MR 上创建 AI Review 评论
 */

/**
 * 为 AI Review 结果创建 GitLab 评论
 * @param comments Review 评论列表
 * @param context MR Review 上下文
 * @param projectInRepository 项目信息
 * @returns 成功创建的评论数量
 */
export async function createReviewComments(
  comments: ReviewComment[],
  context: MRReviewContext,
  projectInRepository: ProjectInRepository,
): Promise<number> {
  const gitLabService = getGitLabService(projectInRepository);
  let successCount = 0;

  // eslint-disable-next-line no-restricted-syntax
  for (const comment of comments) {
    try {
      // eslint-disable-next-line no-await-in-loop
      await createSingleComment(comment, context, gitLabService);
      successCount += 1;
      log.info(`Created review comment on ${comment.filePath}:${comment.lineNumber}`);
    } catch (error) {
      log.error(`Failed to create comment on ${comment.filePath}:${comment.lineNumber}: ${error}`);
    }
  }

  log.info(`Successfully created ${successCount}/${comments.length} review comments`);
  return successCount;
}

/**
 * 创建单个 review 评论
 */
async function createSingleComment(
  comment: ReviewComment,
  context: MRReviewContext,
  gitLabService: ReturnType<typeof getGitLabService>,
): Promise<void> {
  // 找到对应的 diff
  const diff = context.diffs.find((d) => d.filePath === comment.filePath);
  if (!diff) {
    throw new Error(`Diff not found for file: ${comment.filePath}`);
  }

  // 构建评论内容，包含严重程度标记
  const commentBody = formatCommentBody(comment);

  // 构建 diff position
  const position: GqlDiffPositionInput = {
    baseSha: context.baseSha,
    headSha: context.headSha,
    startSha: context.startSha,
    paths: {
      oldPath: diff.oldPath || diff.newPath,
      newPath: diff.newPath,
    },
    newLine: comment.lineNumber,
  };

  // 如果有旧行号，也添加
  if (comment.oldLineNumber) {
    position.oldLine = comment.oldLineNumber;
  }

  // 创建 diff 评论
  await gitLabService.createDiffNote(context.mrId, commentBody, position);
}

/**
 * 格式化评论内容
 */
function formatCommentBody(comment: ReviewComment): string {
  const severityEmoji = {
    error: '🚨',
    warning: '⚠️',
    info: 'ℹ️',
  };

  const emoji = severityEmoji[comment.severity] || 'ℹ️';

  return `${emoji} **AI Code Review** (${comment.severity})

${comment.content}

---
*This comment was generated by GitLab Duo AI Code Review*`;
}
